In [1]:
import numpy as np

# Given list
Lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert list to NumPy array
arr = np.array(Lst)

# Replace odd elements with -2
arr[arr % 2 != 0] = -2 # this condition is to convert the odd numbers of the array with the "-2"

print(arr)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [3]:
import numpy as np

# Given array
arr = np.array([1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7])

# Filter elements in the range from 8 to 15 (inclusive)
result = arr[(arr >= 8) & (arr <= 15)]

print(result)


[ 8  9 10 12]


In [5]:
import numpy as np

# Create a 3x3 array with numbers from 1 to 9
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]] # ":" it means sliceing the array and pick the specific row and column from the array

print(arr)


[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [17]:
import numpy as np

# Given array with NaN values
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                [2.6, 3.3, np.nan, 5.5], 
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the mean of each column ignoring NaN values and round to 2 decimal places
col_mean = np.nanmean(arr, axis=0)
col_mean = np.round(col_mean, 2)

# Find indices where NaN values are located
inds = np.where(np.isnan(arr))

# Replace NaN values with the mean of the respective column
arr[inds] = np.take(col_mean, inds[1])

print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [19]:
import numpy as np

# Given array with NaN values
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                [2.6, 3.3, np.nan, 5.5], 
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the mean of each column ignoring NaN values
col_mean = np.nanmean(arr, axis=0)

# Round the means to 2 decimal places and ensure formatting with trailing zero
col_mean = np.round(col_mean, 2)

# Ensure the means are formatted as strings with one decimal place
col_mean = [f"{mean:.1f}" for mean in col_mean]

# Convert back to numpy array if needed
col_mean = np.array(col_mean, dtype=float)

# Find indices where NaN values are located
inds = np.where(np.isnan(arr))

# Replace NaN values with the mean of the respective column
arr[inds] = np.take(col_mean, inds[1])

print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [27]:
import numpy as np

# Given array with NaN values
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                [2.6, 3.3, np.nan, 5.5], 
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the mean of each column ignoring NaN values
col_mean = np.nanmean(arr, axis=0) # here the "axix = 0" means, i will only calculate the mean verticaly but not in the "horizontaly", but if "axis = 1" then it will calculate the horizontal as well

# The function "np.nanmean" is a part of the "NumPy library" and is used to calculate the mean (average) of an array while ignoring any NaN (Not a Number) values

# Find indices where NaN values are located
inds = np.where(np.isnan(arr)) # "where function checks the number of indices where the nan values are located"

# Replace NaN values with the mean of the respective column
arr[inds] = np.take(col_mean, inds[1])

# Here, inds will be a tuple containing two arrays:-
#The first array (inds[0]) represents the row indices where the NaN values are located.
#The second array (inds[1]) represents the column indices where the NaN values are located.

# Set print options to display one decimal place

np.set_printoptions(formatter={'all': lambda x: f'{x:.1f}'})

# CODE BREAK DOWN:-

# "np.set_printoptions" is a function in NumPy that allows you to modify how NumPy arrays are displayed when you print them.
# "formatter" is a dictionary where the keys specify the type of elements you want to format, and the values define the formatting behavior for those elements.
# In this case, 'all' is the key, which means "apply the formatting to all elements of the array".
# lambda x:  : This defines an anonymous function that takes an argument x (the element to format).
# f'{x:.1f}': This is a formatted string using Python's f-string syntax. It ensures that each element is formatted to 1 decimal place.
# The ".1f" specifies that the number should be formatted as a floating-point number with 1 digit after the decimal point.

# Print the modified array
print(arr)


[[1.3 2.5 3.6 6.0]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [31]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [1, 3, 5]])

# i. Convert the NumPy array to a NumPy matrix

matrix = np.matrix(arr) # coverting matrix to array
print("Matrix:\n", matrix) # printing the converted array to matrix

# ii. Sort the values in the matrix

# Flatten the matrix, sort, and reshape back to the original shape
sorted_matrix = np.sort(matrix, axis=None).reshape(matrix.shape) # "axis = none" ("axis = 0 is y-axis", "axis = 1 is x-axis") will flatten the matrix ( 2D to 1D), the "reshape" will make it reshap to 2D array(to its original shape)

print("Sorted Matrix:\n", sorted_matrix)


Matrix:
 [[2.0 4.0 6.0]
 [1.0 3.0 5.0]]
Sorted Matrix:
 [[1.0 2.0 3.0]
 [4.0 5.0 6.0]]


In [33]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [1, 3, 5]])

# i. Convert the NumPy array to a NumPy matrix
matrix = np.matrix(arr)
print("Matrix:\n", matrix)

Matrix:
 [[2.0 4.0 6.0]
 [1.0 3.0 5.0]]


In [1]:
import os
# Get the current working directory
current_directory = os.getcwd()
print(current_directory)

C:\Users\Dell
